import { Injectable } from '@angular/core';
import {JobExperienceDTO, jobExperienceResponse} from "../../model/api-responses";
import {environment} from "../../../environments/environment";
import {ApiService} from "../mainApi/api.service";
import {Observable} from "rxjs";

const STATIC_JOB_DATA: JobExperienceDTO[] = [
  { "id": 4, "title": "Full-Stack Developer (Intern → Trainee → Junior Backend Developer)", "company": "Ismart (Devana Soft Pvt. Ltd.)", "location": "Kathmandu, Nepal", "employmentType": "full-time", "description": "Contributed to both frontend and backend development at Devana Soft Pvt. Ltd., with progressive responsibility from intern to junior backend developer. During the internship phase, worked on the backend of the Meeting Management System project, then transitioned to Ismart, where I focused on building scalable backend solutions while also contributing to Angular frontend development. Additionally, gained hands-on deployment experience by managing servers through SSH and Docker.", "achievements": ["Developed and optimized RESTful APIs using Spring Boot and Spring MVC for Ismart and internal projects.", "Designed and maintained database schemas to support scalable web applications.", "Contributed to Angular frontend features, improving UI functionality and user workflows.", "Enhanced the Meeting Management System backend by implementing database operations and API endpoints.", "Deployed applications manually to backend servers using SSH and Docker, strengthening deployment and infrastructure knowledge.", "Actively collaborated in agile sprints, ensuring on-time delivery of high-quality features.", "Successfully promoted from Intern → Trainee → Junior Backend Developer based on consistent performance."], "technologiesUsed": ["Java", "Spring Boot", "Spring MVC", "REST APIs", "MySQL", "PostgreSQL", "Angular", "Git", "Agile", "Docker", "SSH"], "startDate": "2024-12-10", "endDate": "present", "isCurrent": true, "displayOrder": 3, "insertUser": "admin", "editUser": "admin", "photos": [] },
  { "id": 6, "title": "Full-Stack Developer", "company": "Personal Project – AI Portfolio Web Application", "location": "Remote", "employmentType": "project", "description": "Designed and deployed a full-stack portfolio web application with integrated AI services. The platform supports multiple users, allowing each to create a personalized portfolio by providing their professional experiences, AI profile, and response preferences, which are stored in a PostgreSQL database. The system not only serves as an interactive personal portfolio but also integrates an AI-powered chatbot that can converse about the user based on their data. A live example is available at www.progress.com.np.", "achievements": ["Developed a responsive Angular frontend to display dynamic, user-specific portfolios.", "Built a scalable Spring Boot backend to manage multi-user data, authentication, and chatbot logic.", "Integrated PostgreSQL database for structured storage of user profiles, experiences, and AI response preferences.", "Implemented an AI-driven chatbot that adapts its responses according to individual user data and preferences.", "Deployed the application publicly, showcasing its ability to handle multiple users while maintaining security and scalability."], "technologiesUsed": ["Angular", "Spring Boot", "Java", "PostgreSQL", "REST APIs", "AI Integration", "langchain4j", "Cloudinary", "Git", "Docker"], "startDate": "2025-08-16", "endDate": "2025-08-30", "isCurrent": false, "displayOrder": 5, "insertUser": "admin", "editUser": "admin", "photos": [] },
  { "id": 2, "title": "Website Developer", "company": "Kipaa", "location": "Online", "employmentType": "freelance", "description": "Built and maintained a professional web application where clients can request engineering services, contact the company, and stay updated on announcements. Currently implementing a separate frontend server using Angular to improve scalability and user experience. Visit: www.kipaa.com.np", "achievements": ["Developed a responsive web interface for clients to browse services and projects.", "Implemented content management features to streamline company updates.", "Improved overall site performance and accessibility for users.", "Began migration of frontend to Angular for better modularity and maintainability."], "technologiesUsed": ["HTML", "CSS", "JavaScript", "PHP", "MySQL", "Angular"], "startDate": "2023-01-01", "endDate": "present", "isCurrent": true, "displayOrder": 1, "insertUser": "admin", "editUser": "N/A", "photos": [] },
  { "id": 5, "title": "Full Stack Developer (College Project 3 - Meal Mapper)", "company": "Nepal Engineering College", "location": "University", "employmentType": "project", "description": "Developed a health-oriented mobile application that integrates machine learning to recognize food items and recommend meals based on nutritional content and user history.", "achievements": ["Built backend services in Python to support machine learning-driven recommendations.", "Developed mobile frontend using Flutter for cross-platform compatibility.", "Implemented a neural network model to recognize food items from image inputs.", "Enhanced user engagement with personalized meal suggestions."], "technologiesUsed": ["Flutter", "Python", "Machine Learning", "Neural Networks", "REST APIs", "Flask", "Dart", "PostgreSQL", "Git"], "startDate": "2024-01-01", "endDate": "2024-12-01", "isCurrent": false, "displayOrder": 4, "insertUser": "admin", "editUser": "N/A", "photos": [] },
  { "id": 3, "title": "Full Stack Developer (College Project 2 - Negotium)", "company": "Nepal Engineering College", "location": "University", "employmentType": "project", "description": "Developed an Android-based e-commerce application for local shops, featuring an offline mode that allows users to browse products and make purchases without an internet connection.", "achievements": ["Built backend services using Java for Android to handle offline purchasing functionality and PHP for server-side operations.", "Implemented offline-first capabilities with SQLite, ensuring smooth user experience without internet connectivity.", "Integrated RESTful APIs for product management, order processing, and data synchronization."], "technologiesUsed": ["Java (Android)", "PHP", "SQLite", "JSON", "REST APIs"], "startDate": "2023-01-01", "endDate": "2024-01-01", "isCurrent": false, "displayOrder": 2, "insertUser": "admin", "editUser": "admin", "photos": [] },
  { "id": 1, "title": "LocatoR for College Project 1", "company": "Nepal Engineering College", "location": "University", "employmentType": "project", "description": "Developed a web application designed to provide location-based reviews where users can recommend new places to visit and stay informed about ongoing events in various locations.", "achievements": ["Designed and implemented backend functionality using PHP to manage user reviews and events.", "Improved user experience with AJAX-powered dynamic updates for seamless interactions.", "Strengthened application reliability with effective database management strategies."], "technologiesUsed": ["PHP", "AJAX", "HTML", "CSS", "JavaScript", "MySQL"], "startDate": "2022-01-01", "endDate": "2023-01-01", "isCurrent": false, "displayOrder": 0, "insertUser": "admin", "editUser": "N/A", "photos": [] }
];

@Injectable({
  providedIn: 'root'
})
export class ExperienceService {

  private userId=environment.userId;

  constructor(private apiService: ApiService) { }

  getExperience():Observable<jobExperienceResponse>{
    return this.apiService.getWithoutAuth<jobExperienceResponse>(`/api/experiences/users/viewAll/${this.userId}`);
  }
}
